(function(){
  const app=document.querySelector('#app'),restaurant=window.PLAData.restaurant('la-nonna');let data=window.PLAData.merged(),products=data.products.filter(p=>p.restaurantId===restaurant.id),categories=data.categories.filter(c=>c.restaurantId===restaurant.id);
  app.innerHTML=`<div class="dashboard-shell"><aside class="sidebar"><a href="index.html" class="wordmark">PLATO</a><nav><a class="side-link active" href="#resumen">Resumen</a><a class="side-link" href="#productos">Productos</a><a class="side-link" href="#categorias">Categorías</a><a class="side-link" href="#qr">QR del menú</a><a class="side-link" href="admin.html">Admin global ↗</a></nav></aside><main class="dash-main"><header class="dash-header"><div><div class="eyebrow">Workspace / ${window.PLA.esc(restaurant.slug)}</div><h1>Hola, ${window.PLA.esc(restaurant.name)}.</h1><p>Una mirada rápida a tu menú digital.</p></div><a class="button primary" href="menu.html?restaurant=${restaurant.slug}">Ver menú público ↗</a></header><div class="local-banner"><strong>Modo estático local.</strong> Los cambios se guardan solo en este navegador y no se sincronizan con Internet ni con otros dispositivos.</div><section class="stat-grid" id="resumen"><div class="stat-card"><small>Productos publicados</small><strong id="product-count"></strong></div><div class="stat-card"><small>Visitas locales</small><strong id="visit-count"></strong></div><div class="stat-card"><small>Interacciones guardadas</small><strong id="event-count"></strong></div></section><section class="panel" id="productos"><div class="panel-heading"><h2>Productos del menú</h2><button class="button secondary" id="new-product">Nuevo producto</button></div><form class="form-grid" id="product-form" hidden><input class="field" id="product-name" required placeholder="Nombre del producto" aria-label="Nombre del producto"><input class="field" id="product-price" required type="number" min="0" placeholder="Precio ARS" aria-label="Precio"><button class="button primary" type="submit">Crear</button></form><div id="product-list"></div></section><section class="panel" id="categorias" style="margin-top:16px"><div class="panel-heading"><h2>Categorías</h2></div><p class="muted">${categories.map(c=>window.PLA.esc(c.name)).join(' · ')}</p><small class="muted">La edición avanzada queda guardada localmente en esta demo.</small></section><section class="panel" id="qr" style="margin-top:16px"><div class="panel-heading"><h2>QR del menú</h2></div><div class="qr-box"><canvas id="qr-canvas" width="180" height="180">QR</canvas><div><p class="muted">Este enlace es compatible con GitHub Pages. Podés descargar la imagen cuando cargue o imprimir esta vista.</p><code class="qr-url" id="qr-url"></code><a class="button ghost" id="download-qr" download="plato-la-nonna-qr.png" hidden>Descargar QR</a></div></div></section></main></div>`;
  const list=document.querySelector('#product-list');
  function save(){const next=window.PLAData.updateData('products',products.concat(data.products.filter(p=>p.restaurantId!==restaurant.id)));data=next;products=data.products.filter(p=>p.restaurantId===restaurant.id);render();}
  function render(){const events=window.PLAStorage.read('analytics',[]);document.querySelector('#product-count').textContent=products.filter(p=>p.available).length;document.querySelector('#visit-count').textContent=events.filter(e=>e.name==='menu_view').length;document.querySelector('#event-count').textContent=events.length;list.innerHTML=products.map(p=>`<div class="product-row"><div class="row-thumb" style="background-image:url('${window.PLA.esc(p.image)}')"></div><div class="row-main"><strong>${window.PLA.esc(p.name)}</strong><span>${window.PLA.esc((categories.find(c=>c.id===p.categoryId)||{}).name||'Sin categoría')} · ${window.PLA.money(p.price)}</span></div><button class="status ${p.available?'on':'off'}" data-toggle="${p.id}">${p.available?'Publicado':'Pausado'}</button></div>`).join('');list.querySelectorAll('[data-toggle]').forEach(button=>button.addEventListener('click',()=>{const product=products.find(item=>item.id===button.dataset.toggle);product.available=!product.available;save();}));}
  document.querySelector('#new-product').addEventListener('click',()=>{const form=document.querySelector('#product-form');form.hidden=!form.hidden;});
  document.querySelector('#product-form').addEventListener('submit',event=>{event.preventDefault();const name=document.querySelector('#product-name').value.trim(),price=Number(document.querySelector('#product-price').value);if(!name||!price)return;const slug=name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');products.unshift({id:'local-'+Date.now(),restaurantId:restaurant.id,categoryId:categories[0].id,name,slug,description:'Producto local pendiente de completar.',price,image:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=82',model3d:'',model3dEnabled:false,ingredients:[],available:true});save();event.target.reset();event.target.hidden=true;});
  const url=window.PLAQR.url(restaurant);document.querySelector('#qr-url').textContent=url;window.PLAQR.render(document.querySelector('#qr-canvas'),url);render();
})();
