(function(){
  const app=document.querySelector('#app'), restaurant=window.PLAData.restaurant(window.PLA.params.get('restaurant')||'la-nonna'), product=window.PLAData.product(window.PLA.params.get('product'));
  if(!restaurant||!product||product.restaurantId!==restaurant.id){app.innerHTML='<main class="container landing"><h1 class="serif">Producto no encontrado</h1><a class="view-link" href="menu.html?restaurant=la-nonna">Volver al menú</a></main>';return;}
  const category=window.PLAData.categories(restaurant.id).find(c=>c.id===product.categoryId); window.PLA.trackEvent('product_view',{productId:product.id});
  app.innerHTML=`<main class="container"><header class="topbar"><a class="wordmark" href="index.html">PLATO</a><span class="pill">${window.PLA.esc(restaurant.name)}</span></header><section class="detail-shell"><a class="back-link" href="menu.html?restaurant=${encodeURIComponent(restaurant.slug)}">← Volver al menú</a><div class="detail-grid"><div class="viewer" id="viewer"></div><div class="detail-copy"><div class="eyebrow">${window.PLA.esc(category?category.name:'Producto')}</div><h1 class="serif">${window.PLA.esc(product.name)}</h1><p class="lead">${window.PLA.esc(product.description)}</p><div class="detail-price">${window.PLA.money(product.price)}</div><div class="ingredients">${product.ingredients.map(i=>`<span class="ingredient">${window.PLA.esc(i)}</span>`).join('')}</div><div class="actions"><button class="button primary" id="add">Agregar al pedido</button><button class="button secondary" id="ar">Ver en mi mesa</button><a class="button ghost" href="pedido.html">Ver pedido</a></div><div class="notice" data-ar-notice>La fotografía es el fallback visual. Los modelos GLB/GLTF se cargan solo cuando el restaurante publica uno.</div></div></div></section></main>`;
  window.PLAThree.render(document.querySelector('#viewer'),product);
  document.querySelector('#add').addEventListener('click',e=>{window.PLA.addToCart(product);e.currentTarget.textContent='Agregado ✓';});
  document.querySelector('#ar').addEventListener('click',()=>window.PLAAR.open(product));
})();
