export type DemoProduct = { slug:string; name:string; description:string; price:number; category:string; image:string; ingredients:string[]; available:boolean; has3d:boolean; arEnabled:boolean };
export const demoRestaurant = { name:"La Nonna", slug:"la-nonna", description:"Cocina italiana de barrio, hecha sin apuro y servida con cariño.", cover:"https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1800&q=85", logo:"LN", address:"Palermo, Buenos Aires", categories:["Pizzas","Pastas","Postres","Bebidas"] };
export const demoProducts: DemoProduct[] = [
  {slug:"pizza-napolitana",name:"Pizza Napolitana",description:"Mozzarella fior di latte, tomate San Marzano y albahaca fresca.",price:11000,category:"Pizzas",image:"https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=900&q=82",ingredients:["Tomate San Marzano","Fior di latte","Albahaca"],available:true,has3d:false,arEnabled:false},
  {slug:"pizza-margherita",name:"Pizza Margherita",description:"La simpleza perfecta: tomate, mozzarella, albahaca y oliva.",price:9800,category:"Pizzas",image:"https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=900&q=82",ingredients:["Tomate","Mozzarella","Aceite de oliva"],available:true,has3d:false,arEnabled:false},
  {slug:"pasta-carbonara",name:"Pasta Carbonara",description:"Spaghetti al dente, guanciale, pecorino romano y pimienta negra.",price:13500,category:"Pastas",image:"https://images.unsplash.com/photo-1612874742237-6526221588e3?auto=format&fit=crop&w=900&q=82",ingredients:["Spaghetti","Guanciale","Pecorino"],available:true,has3d:false,arEnabled:false},
  {slug:"lasagna",name:"Lasagna de la Nonna",description:"Capas de pasta fresca, ragú cocido lento y bechamel gratinada.",price:14200,category:"Pastas",image:"https://images.unsplash.com/photo-1574894709920-11b28e7367e3?auto=format&fit=crop&w=900&q=82",ingredients:["Pasta fresca","Ragú","Bechamel"],available:true,has3d:false,arEnabled:false},
  {slug:"tiramisu",name:"Tiramisú",description:"Mascarpone, café espresso y cacao amargo en capas suaves.",price:7200,category:"Postres",image:"https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=900&q=82",ingredients:["Mascarpone","Espresso","Cacao"],available:true,has3d:false,arEnabled:false},
  {slug:"cafe-latte",name:"Café Latte",description:"Espresso intenso con leche vaporizada y una espuma sedosa.",price:4800,category:"Bebidas",image:"https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=900&q=82",ingredients:["Espresso","Leche"],available:true,has3d:false,arEnabled:false},
];
export function formatPrice(value:number){ return new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0}).format(value); }
